### ISSUE TITLE
Should useState be updated to *not* use the setter from MutableState?

### ISSUE THREAD

**Issue by thevoiceless** [pavi2410/useCompose#6]
Context: https://www.reddit.com/r/androiddev/comments/rqdv5g/there_are_three_ways_to_declare_a_mutablestate/

tl;dr:
```kt
@Composable
fun Test() {
    val (value, setValue) = remember { mutableStateOf(0) }
    println(value)
    setValue(value + 1)
    println(value)
}
```
will output
```
0
0
```

In light of that, perhaps [useState](https://github.com/pavi2410/useCompose/blob/main/react/src/main/java/me/pavi2410/useCompose/react/hooks.kt#L14) should be updated? Something like:
```kt
@Composable
fun <T> useState(defaultValue: T): Pair<T, (T) -> Unit> {
    var state by remember { mutableStateOf(defaultValue) }
    return Pair(state, { state = it }) // or `return state to { state = it }`
}
```

**Comment by pavi2410** [comment]
Thanks for reporting this issue. I'll try reproducing this on Compose (with and without useCompose) as well as React to test the appropriate behaviour.

**Comment by pavi2410** [comment]
Tested
- React - it turns out to be an infinite rendering issue.
    ```
    0
    0
    1
    1
    2
    2
    ...
    ```
- with useCompose:
    ```
    0
    0
    ```
- w/o useCompose:
    ```
    0
    1
    ```
- your proposed solution works the same as the current version

**Comment by thevoiceless** [comment]
Interesting! Thanks for looking into it :)
